SET SCHEMA 'bumsoftdb';

CREATE SEQUENCE IF NOT EXISTS USER_SEQ
    START WITH 1000
    INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS ROLE_SEQ
    START WITH 1000
    INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS OPERATION_SEQ
    START WITH 1000
    INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS ACCOUNT_SEQ
    START WITH 1000
    INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS TRANSACTION_SEQ
    START WITH 1000
    INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS REFERENCE_ENTITY_SEQ
    START WITH 1000
    INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS SUBSCRIPTION_SEQ
    START WITH 1000
    INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS INCOME_STATEMENT_SEQ
    START WITH 1000
    INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS PAYMENT_INFO_SEQ
    START WITH 1000
    INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS CREDIT_CARD_SEQ
    START WITH 1000
    INCREMENT BY 1;